Benchmark:
  CUDA_VISIBLE_DEVICES: "7"
  model: &model "facebook/opt-6.7b"
  Hardware: 
    name: "a100-80gb"
    peak_power: NULL
    average_power: NULL
  prompt_size: [128, 256, 512, 1024]
  batch_size: [1,2,4,16,32]
  token_size: [128, 256, 512, 1024]
  result_path: "./results/opt-6.7b.csv"
  device: &device "cuda"  

Model:
  pretrained_model_name_or_path: *model
  cache_dir: "/root/model_hub/"
  torch_dtype: "float16"
  device: *device
  device_map: "auto"
  trust_remote_code: true

Tokenizer:
  pretrained_model_name_or_path: *model
  cache_dir: "/root/model_hub/"
  trust_remote_code: true